### ISSUE TITLE
First working draft of shell

### ISSUE THREAD

**Issue by mkai5** [cmsc22000-project-2018/support-tools#17]

**Comment by MaxineK36** [comment]
I spent a total of about 5 and a half hours on this task, between adapting the shell and then setting up and including the visualizations that Marco created, which included creating lots of dummy files to deal with the fact that we don't yet have tries.

**Comment by richard-pei** [comment]
I spent 2 hours on this task, updating the shell to fit the visualizations that Harold created, including researching doing further research of how to implement subtree visualization properly, as its inputs would be different from the other three visualizations.
