### ISSUE TITLE
Communicate with API Team to Discuss Necessary Features for Visualizations

### ISSUE THREAD

**Issue by mkai5** [cmsc22000-project-2018/support-tools#25]
As of 5.8 we reached out to the API team to discuss what we need the API to provide for our visualizations / shell for experimenting with tries.

**Comment by ecrowdus** [comment]
created a #apisupport channel on slack with AK Alilonu on the API team

**Comment by ecrowdus** [comment]
Marco and I just met with AK to discuss the API situation regarding. He will discuss with his team and we will re-convene on Monday after Marco & I meet with the Trie team.

**Comment by ecrowdus** [comment]
After meeting with AK and communicating with him via Slack and in person, we explained the updated requirements that we had provided to the Trie team. Our teams are now on the same page about requirements going forward.
