### ISSUE TITLE
Initial Design Doc

### ISSUE THREAD

**Issue by ecrowdus** [cmsc22000-project-2018/support-tools#5]

**Comment by ecrowdus** [comment]
As of 10/24/18, first draft has been completed

**Comment by ecrowdus** [comment]
actual: long

**Comment by richard-pei** [comment]
After Elizabeth and Marco wrote the initial first draft of the Design Doc, I helped to develop the UML Diagram as well as update the functions within the Design Doc. Each of these tasks took about 20 minutes.
