### ISSUE TITLE
Change the "help" feature to also take arguments

### ISSUE THREAD

**Issue by MaxineK36** [cmsc22000-project-2018/support-tools#64]

**Comment by richard-pei** [comment]
I added a more standard command-line help argument based on standard guidelines for writing help.

**Comment by MaxineK36** [comment]
I added support for using help with various arguments to get more detailed help from within the shell

**Comment by MaxineK36** [comment]
In total, we spent 3-4 hours working on this, including a slight re-structuring of the naming system and time determining which of our functions would be referred to by each command. 
See pull request #67
