### ISSUE TITLE
work on integrating shell with api

### ISSUE THREAD

**Issue by ecrowdus** [cmsc22000-project-2018/support-tools#95]
still waiting on the trie implementations of the viz fns, but we are working on making a trie through the redis server to use fns like insert_trie, etc.

**Comment by ecrowdus** [comment]
--set up vm to connect to redis
--figured out how to modify makefile so it accessed the api (i.e. adding lib command)
--modified fns to align with redis fn headers

**Comment by ecrowdus** [comment]
--because it's not looking like integration of our viz fns is going to happen in time for the presentation, we are now working on integrating just to access a trie, which we will demo in our presentation and follow up with a demo of our local shell; the API's functions currently do not allow us to access the parts of a trie we need for our viz functions, which is why we are unable to partially integrate

**Comment by MaxineK36** [comment]
We ended up making two versions of the trie files, one to use with the API trie_insert and trie_new and one to use with viz_functions. We also got the Makefile to compile locally with the library. 
This ended up taking much much longer than anticipated.
